import { Project, BlogPost } from "@/types";

export const staticProjects: Project[] = [
  {
    slug: "grade-management-system",
    title: "University Grade Management System",
    description: "A comprehensive web-based system for managing student grades, courses, and academic records for Woldia University.",
    longDescription: "Built with PHP and MySQL, this system handles student enrollment, grade entry by instructors, GPA calculation, transcript generation, and administrative reporting.",
    techStack: ["PHP", "MySQL", "HTML/CSS", "JavaScript", "Bootstrap"],
    liveUrl: "https://studentgradesystem.free.nf/",
    imageColor: "from-amber-500/20 to-orange-600/20",
    featured: true,
    status: "completed",
    year: "2024",
    challenges: "Implementing role-based access control for students, instructors, and admins while keeping the UI intuitive.",
    lessons: "Deepened understanding of relational database design, session management, and building multi-role web applications.",
  },
  {
    slug: "ecommerce-app",
    title: "Beki E-Commerce Platform",
    description: "A modern full-stack e-commerce application with product listings, cart management, and a clean checkout experience.",
    longDescription: "Built with Next.js and deployed on Vercel, featuring product management, shopping cart, responsive design, and a seamless user experience.",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    liveUrl: "https://beki-ecommerce-oy9z.vercel.app/",
    githubUrl: "https://github.com/berekettesfayegetie89-ethiopia",
    imageColor: "from-emerald-500/20 to-teal-600/20",
    featured: true,
    status: "completed",
    year: "2024",
    challenges: "Managing complex cart state and building a smooth product browsing experience with filters.",
    lessons: "Gained strong proficiency in Next.js App Router, React state management, and Tailwind CSS.",
  },
  {
    slug: "dormitory-management",
    title: "Dormitory Management System",
    description: "A system for managing university dormitory room assignments, student records, and maintenance requests.",
    techStack: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
    imageColor: "from-blue-500/20 to-indigo-600/20",
    featured: false,
    status: "in-progress",
    year: "2025",
  },
  {
    slug: "portfolio",
    title: "Developer Portfolio",
    description: "This very portfolio — built with Next.js, TypeScript, Tailwind CSS, and Framer Motion with a Decap CMS backend.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Decap CMS"],
    githubUrl: "https://github.com/berekettesfayegetie89-ethiopia",
    imageColor: "from-purple-500/20 to-pink-600/20",
    featured: false,
    status: "completed",
    year: "2025",
  },
];

export const staticBlogPosts: BlogPost[] = [
  {
    slug: "my-journey-into-programming",
    title: "My Journey Into Programming: From Zero to Full-Stack",
    excerpt: "How I went from knowing nothing about code to building real university systems in Ethiopia — the challenges, breakthroughs, and what keeps me going.",
    date: "2025-01-15",
    readTime: "5 min read",
    tags: ["Journey", "Learning", "Motivation"],
  },
  {
    slug: "why-i-chose-nextjs",
    title: "Why I Chose Next.js Over Plain React",
    excerpt: "After building projects in both React and Next.js, here's why I think Next.js is the right choice for most web applications today.",
    date: "2025-02-10",
    readTime: "4 min read",
    tags: ["Next.js", "React", "Web Dev"],
  },
  {
    slug: "building-grade-management",
    title: "Building a Grade Management System for My University",
    excerpt: "The story behind building a real academic management system — the technical decisions, database design, and what I learned along the way.",
    date: "2025-03-20",
    readTime: "7 min read",
    tags: ["PHP", "MySQL", "Project"],
  },
];
